# Generated by Django 2.2.3 on 2020-09-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custormer',
            name='qq',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
