# Generated by Django 2.2.3 on 2020-09-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_custormer_qq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custormer',
            name='qq',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
